import { Inter } from "next/font/google";
import { Montserrat } from 'next/font/google'
import "./globals.css";
import { Providers } from "@/redux/providers";

const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({
  subsets: ['latin'],
  style: ['normal'],
  weight: ['400'],
})

export const metadata = {
  title: "Cryptonite",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className+" "+montserrat.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
